version: '3'

services:
  rabbitmq3:
    container_name: "rabbitmq"
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ea_project
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"



  event-service:
    build:
      context: .
      dockerfile: Dockerfile-event-service
    image: event-service:latest
    ports:
      - "8085:8085"
    depends_on:
      - mysql

  job-service:
    build:
      context: .
      dockerfile: Dockerfile-job-service
    image: job-service:latest
    ports:
      - "8084:8084"
    depends_on:
      - mysql

  log-service:
    build:
      context: .
      dockerfile: Dockerfile-log-service
    image: log-service:latest
    ports:
      - "8082:8082"
    depends_on:
      - mysql

  news-service:
    build:
      context: .
      dockerfile: Dockerfile-news-service
    image: news-service:latest
    ports:
      - "8086:8086"
    depends_on:
      - mysql

  student-service:
    build:
      context: .
      dockerfile: Dockerfile-student-service
    image: student-service:latest
    ports:
      - "8082:8082"
    depends_on:
      - mysql

  survey-surveyresponse-service:
    build:
      context: .
      dockerfile: Dockerfile-survey-surveyresponse-service
    image: survey-surveyresponse-service:latest
    ports:
      - "8083:8083"
    depends_on:
      - mysql

  user-service:
    build:
      context: .
      dockerfile: Dockerfile-user-service
    image: user-service:latest
    ports:
      - "8081:8081"
    depends_on:
      - mysql

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile-api-gateway
    image: api-gateway:latest
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server
      - configuration-service

  configuration-service:
    build:
      context: .
      dockerfile: Dockerfile-configuration-service
    image: configuration-service:latest
    ports:
      - "8888:8888"
    depends_on:
      - discovery-server

  discovery-server:
    build:
      context: .
      dockerfile: Dockerfile-discovery-server
    image: discovery-server:latest
    ports:
      - "8761:8761"
