version: '3'

services:
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      - '5672:5672'
      - '15672:15672'

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ea_project
      MYSQL_USER: root
      MYSQL_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: 1
    ports:
      - "3307:3306"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus

  event-service:
    build:
      context: ./Event-Service
      dockerfile: Dockerfile-event-service
    image: event-service:latest
    ports:
      - "8085:8085"
    depends_on:
      - mysql
      - grafana
      - prometheus

  job-service:
    build:
      context: ./Job-Service
      dockerfile: Dockerfile-job-service
    image: job-service:latest
    ports:
      - "8084:8084"
    depends_on:
      - mysql
      - grafana
      - prometheus

  log-service:
    build:
      context: ./Log-Service
      dockerfile: Dockerfile-log-service
    image: log-service:latest
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - grafana
      - prometheus

  news-service:
    build:
      context: ./News-Service
      dockerfile: Dockerfile-news-service
    image: news-service:latest
    ports:
      - "8086:8086"
    depends_on:
      - mysql
      - grafana
      - prometheus

  student-service:
    build:
      context: ./Student-service
      dockerfile: Dockerfile-student-service
    image: student-service:latest
    ports:
      - "8083:8083"
    depends_on:
      - mysql
      - grafana
      - prometheus

  survey-surveyresponse-service:
    build:
      context: ./Surevy-surveyresponse-service
      dockerfile: Dockerfile-survey-surveyresponse-service
    image: survey-surveyresponse-service:latest
    ports:
      - "8087:8087"
    depends_on:
      - mysql
      - grafana
      - prometheus

  user-service:
    build:
      context: ./User-Service
      dockerfile: Dockerfile-user-service
    image: user-service:latest
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - grafana
      - prometheus

  api-gateway:
    build:
      context: ./api-gatway
      dockerfile: Dockerfile-api-gateway
    image: api-gateway:latest
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server
      - configuration-service

  configuration-service:
    build:
      context: ./configuration-service
      dockerfile: Dockerfile-configuration-service
    image: configuration-service:latest
    ports:
      - "8888:8888"
    depends_on:
      - discovery-server

  discovery-server:
    build:
      context: ./discovery-server
      dockerfile: Dockerfile-discovery-server
    image: discovery-server:latest
    ports:
      - "8761:8761"

volumes:
  grafana-data:
  prometheus-data:
